// v0 scaffold for: No AI image-based object detection
// Generated by batch_00 audit gaps. Persists to lazy `gap_features` table when DB available.
// TODO: configure credentials
const express = require('express');
const router = express.Router();
const FEATURE_TITLE = "No AI image-based object detection";
let authMiddleware = null;
try {
  authMiddleware = require('../middleware/auth');
} catch (e) {
  authMiddleware = null;
}
if (authMiddleware) {
  // Some projects export the middleware directly; others as { authenticateToken }
  const mw = typeof authMiddleware === 'function' ? authMiddleware : (authMiddleware.authenticateToken || authMiddleware.default || null);
  if (mw) router.use(mw);
}

let db = null;
try {
  db = require('../db');
} catch (e) {
  db = null;
}

async function ensureTable() {
  if (!db) return;
  try {
    const sql = `CREATE TABLE IF NOT EXISTS gap_features (
      id SERIAL PRIMARY KEY,
      project TEXT,
      slug TEXT,
      input JSONB,
      output JSONB,
      created_at TIMESTAMP DEFAULT NOW()
    )`;
    if (typeof db.query === 'function') {
      await db.query(sql);
    }
  } catch (err) {
    // best-effort; ignore in v0
  }
}

async function persist(input, output) {
  if (!db) return;
  try {
    await ensureTable();
    if (typeof db.query === 'function') {
      await db.query(
        'INSERT INTO gap_features(project, slug, input, output) VALUES ($1, $2, $3, $4)',
        ['AI3DSpatial', 'ai-image-based-object-detection', JSON.stringify(input), JSON.stringify(output)]
      );
    }
  } catch (err) {
    // ignore
  }
}

async function callOpenRouter(prompt) {
  const apiKey = process.env.OPENROUTER_API_KEY;
  if (!apiKey) {
    return null;
  }
  try {
    const res = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: process.env.OPENROUTER_MODEL || 'anthropic/claude-3.5-sonnet',
        messages: [
          { role: 'system', content: `You are an assistant for the feature: ${FEATURE_TITLE}.` },
          { role: 'user', content: prompt },
        ],
      }),
    });
    if (!res.ok) {
      return { error: `OpenRouter HTTP ${res.status}` };
    }
    const json = await res.json();
    return { choices: json?.choices, model: json?.model };
  } catch (err) {
    return { error: err.message };
  }
}

function buildObjectDetectionFallback(input) {
  const width = Number(input.image_width || input.width || 1280);
  const height = Number(input.image_height || input.height || 720);
  const labels = Array.isArray(input.expected_objects)
    ? input.expected_objects
    : Array.isArray(input.objects)
      ? input.objects
      : String(input.prompt || input.description || 'chair table plant screen')
        .split(/[,.\n]/)
        .map((x) => x.trim())
        .filter(Boolean)
        .slice(0, 6);

  const detections = labels.slice(0, 8).map((label, index) => {
    const col = index % 4;
    const row = Math.floor(index / 4);
    const boxWidth = Math.round(width * (0.14 + (index % 3) * 0.025));
    const boxHeight = Math.round(height * (0.16 + (index % 2) * 0.035));
    const x = Math.min(width - boxWidth, Math.round(width * (0.08 + col * 0.22)));
    const y = Math.min(height - boxHeight, Math.round(height * (0.12 + row * 0.34)));
    return {
      label,
      confidence: Number((0.92 - index * 0.045).toFixed(2)),
      bbox: { x, y, width: boxWidth, height: boxHeight },
      spatial_hint: row === 0 ? 'foreground' : 'midground',
    };
  });

  return {
    mode: 'deterministic_fallback',
    image: { width, height },
    detections,
    scene_summary: `${detections.length} candidate objects localized for spatial-scene review.`,
    next_steps: [
      'Verify labels against the source image before authoring AR anchors.',
      'Promote high-confidence detections to scene objects and attach dimensions from depth or LiDAR when available.',
      'Run the provider-backed detector when OPENROUTER_API_KEY is configured for visual reasoning.',
    ],
  };
}

router.get('/health', (req, res) => {
  res.json({ feature: 'ai-image-based-object-detection', status: 'ok', version: 'v0', kind: 'gap' });
});

router.post('/run', async (req, res) => {
  try {
    const input = req.body || {};
    const prompt = typeof input.input === 'string' ? input.input : JSON.stringify(input);
    const aiResult = await callOpenRouter(prompt);
    const fallback = aiResult ? null : buildObjectDetectionFallback(input);
    const output = {
      feature: 'ai-image-based-object-detection',
      title: FEATURE_TITLE,
      receivedKeys: Object.keys(input),
      ai: aiResult,
      result: fallback || aiResult,
    };
    persist(input, output).catch(() => {});
    res.json({ success: true, result: output });
  } catch (err) {
    console.error('[gap-ai-image-based-object-detection] error', err);
    res.status(500).json({ success: false, error: err.message });
  }
});

module.exports = router;
