export const FEATURES = [
  {
    key: 'models3d',
    title: '3D Models',
    description: 'Generate and manage 3D models with AI-powered creation tools',
    icon: '\u2B21',
    color: '#6366f1',
    endpoint: '/api/models3d',
    aiEndpoint: '/api/ai/generate-3d-model',
    aiPromptHint: 'Describe the 3D model you want to generate (e.g., "A detailed steampunk airship with brass propellers")',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'format', label: 'Format' },
      { key: 'vertices', label: 'Vertices', type: 'number' },
      { key: 'polygons', label: 'Polygons', type: 'number' },
      { key: 'file_size', label: 'Size' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'name', label: 'Name', required: true },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'format', label: 'Format', type: 'select', options: ['FBX', 'OBJ', 'GLTF', 'USD', 'STL'] },
      { key: 'vertices', label: 'Vertices', type: 'number' },
      { key: 'polygons', label: 'Polygons', type: 'number' },
      { key: 'file_size', label: 'File Size' },
      { key: 'status', label: 'Status', type: 'select', options: ['ready', 'processing', 'error'] },
    ],
  },
  {
    key: 'ar-scenes',
    title: 'AR Scenes',
    description: 'Create augmented reality scenes with tracking and interaction',
    icon: '\u{1F4F1}',
    color: '#8b5cf6',
    endpoint: '/api/ar-scenes',
    aiEndpoint: '/api/ai/generate-ar-scene',
    aiPromptHint: 'Describe the AR scene you want to create (e.g., "An AR furniture placement app for a living room")',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'scene_type', label: 'Type' },
      { key: 'target_platform', label: 'Platform' },
      { key: 'tracking_type', label: 'Tracking' },
      { key: 'objects_count', label: 'Objects', type: 'number' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'name', label: 'Name', required: true },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'scene_type', label: 'Scene Type' },
      { key: 'target_platform', label: 'Platform', type: 'select', options: ['iOS', 'Android', 'iOS/Android'] },
      { key: 'tracking_type', label: 'Tracking Type', type: 'select', options: ['Plane Detection', 'Image Tracking', 'Object Tracking', 'Face Tracking', 'Body Tracking', 'Visual SLAM', 'GPS + Plane'] },
      { key: 'objects_count', label: 'Objects Count', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'published', 'archived'] },
    ],
  },
  {
    key: 'vr-environments',
    title: 'VR Environments',
    description: 'Design immersive virtual reality environments and experiences',
    icon: '\u{1F3AE}',
    color: '#a855f7',
    endpoint: '/api/vr-environments',
    aiEndpoint: '/api/ai/generate-vr-environment',
    aiPromptHint: 'Describe the VR environment (e.g., "A serene Japanese zen garden for meditation VR")',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'environment_type', label: 'Type' },
      { key: 'platform', label: 'Platform' },
      { key: 'resolution', label: 'Resolution' },
      { key: 'fps_target', label: 'FPS', type: 'number' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'name', label: 'Name', required: true },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'environment_type', label: 'Environment Type' },
      { key: 'platform', label: 'Platform', type: 'select', options: ['Meta Quest 3', 'SteamVR', 'PSVR2', 'Apple Vision Pro'] },
      { key: 'resolution', label: 'Resolution', type: 'select', options: ['1080p per eye', '4K per eye', '8K per eye'] },
      { key: 'fps_target', label: 'FPS Target', type: 'number' },
      { key: 'interactive_elements', label: 'Interactive Elements', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'published', 'archived'] },
    ],
  },
  {
    key: 'textures',
    title: 'Textures',
    description: 'AI-powered texture generation with PBR material support',
    icon: '\u{1F3A8}',
    color: '#ec4899',
    endpoint: '/api/textures',
    aiEndpoint: '/api/ai/generate-texture',
    aiPromptHint: 'Describe the texture (e.g., "Weathered copper with green patina, PBR metallic workflow")',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'texture_type', label: 'Type' },
      { key: 'resolution', label: 'Resolution' },
      { key: 'format', label: 'Format' },
      { key: 'seamless', label: 'Seamless', type: 'boolean' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'name', label: 'Name', required: true },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'texture_type', label: 'Texture Type' },
      { key: 'resolution', label: 'Resolution', type: 'select', options: ['512x512', '1024x1024', '2048x2048', '4096x4096', '8192x4096'] },
      { key: 'format', label: 'Format', type: 'select', options: ['PNG', 'JPG', 'EXR', 'TIFF'] },
      { key: 'seamless', label: 'Seamless', type: 'checkbox' },
      { key: 'pbr_enabled', label: 'PBR Enabled', type: 'checkbox' },
      { key: 'status', label: 'Status', type: 'select', options: ['ready', 'processing', 'error'] },
    ],
  },
  {
    key: 'animations',
    title: '3D Animations',
    description: 'Create and manage 3D animations with keyframe and procedural tools',
    icon: '\u{1F3AC}',
    color: '#f59e0b',
    endpoint: '/api/animations',
    aiEndpoint: '/api/ai/generate-animation',
    aiPromptHint: 'Describe the animation (e.g., "A smooth walk cycle for a bipedal robot character")',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'animation_type', label: 'Type' },
      { key: 'duration_seconds', label: 'Duration (s)', type: 'number' },
      { key: 'frame_rate', label: 'FPS', type: 'number' },
      { key: 'keyframes', label: 'Keyframes', type: 'number' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'name', label: 'Name', required: true },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'animation_type', label: 'Animation Type' },
      { key: 'duration_seconds', label: 'Duration (seconds)', type: 'number' },
      { key: 'frame_rate', label: 'Frame Rate', type: 'number' },
      { key: 'keyframes', label: 'Keyframes', type: 'number' },
      { key: 'loop_enabled', label: 'Loop Enabled', type: 'checkbox' },
      { key: 'status', label: 'Status', type: 'select', options: ['ready', 'processing', 'error'] },
    ],
  },
  {
    key: 'point-clouds',
    title: 'Point Clouds',
    description: 'Process and analyze 3D point cloud data from LiDAR and photogrammetry',
    icon: '\u2601',
    color: '#14b8a6',
    endpoint: '/api/point-clouds',
    aiEndpoint: '/api/ai/analyze-point-cloud',
    aiPromptHint: 'Describe the point cloud analysis (e.g., "Analyze a LiDAR scan of a bridge for structural defects")',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'point_count', label: 'Points', type: 'number' },
      { key: 'density', label: 'Density' },
      { key: 'source_type', label: 'Source' },
      { key: 'file_size', label: 'Size' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'name', label: 'Name', required: true },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'point_count', label: 'Point Count', type: 'number' },
      { key: 'density', label: 'Density', type: 'select', options: ['Low', 'Medium', 'High', 'Ultra High'] },
      { key: 'source_type', label: 'Source Type', type: 'select', options: ['Aerial LiDAR', 'Terrestrial LiDAR', 'Mobile LiDAR', 'Drone LiDAR', 'Photogrammetry'] },
      { key: 'coordinate_system', label: 'Coordinate System' },
      { key: 'file_size', label: 'File Size' },
      { key: 'status', label: 'Status', type: 'select', options: ['processed', 'processing', 'error'] },
    ],
  },
  {
    key: 'mesh-optimization',
    title: 'Mesh Optimization',
    description: 'Optimize 3D meshes with polygon reduction and quality preservation',
    icon: '\u25B3',
    color: '#06b6d4',
    endpoint: '/api/mesh-optimization',
    aiEndpoint: '/api/ai/optimize-mesh',
    aiPromptHint: 'Describe the mesh optimization task (e.g., "Optimize a 500K poly character model for mobile VR")',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'original_polygons', label: 'Original', type: 'number' },
      { key: 'optimized_polygons', label: 'Optimized', type: 'number' },
      { key: 'reduction_percent', label: 'Reduction %', type: 'number' },
      { key: 'quality_score', label: 'Quality', type: 'number' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'name', label: 'Name', required: true },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'original_polygons', label: 'Original Polygons', type: 'number' },
      { key: 'optimized_polygons', label: 'Optimized Polygons', type: 'number' },
      { key: 'reduction_percent', label: 'Reduction %', type: 'number' },
      { key: 'quality_score', label: 'Quality Score', type: 'number' },
      { key: 'algorithm', label: 'Algorithm', type: 'select', options: ['Quadric Edge Collapse', 'Progressive Mesh', 'Vertex Clustering', 'Feature Preserving', 'Instant Meshes', 'Hierarchical LOD', 'Billboard LOD', 'Manual Retopology'] },
      { key: 'status', label: 'Status', type: 'select', options: ['completed', 'processing', 'error'] },
    ],
  },
  {
    key: 'spatial-mapping',
    title: 'Spatial Mapping',
    description: 'Map and digitize physical spaces with precision sensors',
    icon: '\u{1F5FA}',
    color: '#10b981',
    endpoint: '/api/spatial-mapping',
    aiEndpoint: '/api/ai/generate-spatial-map',
    aiPromptHint: 'Describe the spatial mapping task (e.g., "Map a retail store for AR product placement")',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'area_sqm', label: 'Area (m\u00B2)', type: 'number' },
      { key: 'resolution', label: 'Resolution' },
      { key: 'mapping_type', label: 'Type' },
      { key: 'accuracy', label: 'Accuracy' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'name', label: 'Name', required: true },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'area_sqm', label: 'Area (sq meters)', type: 'number' },
      { key: 'resolution', label: 'Resolution' },
      { key: 'mapping_type', label: 'Mapping Type', type: 'select', options: ['Indoor', 'Outdoor'] },
      { key: 'sensor_type', label: 'Sensor Type', type: 'select', options: ['LiDAR', 'Depth Camera', 'Drone LiDAR'] },
      { key: 'accuracy', label: 'Accuracy' },
      { key: 'status', label: 'Status', type: 'select', options: ['mapped', 'processing', 'error'] },
    ],
  },
  {
    key: 'object-detection',
    title: '3D Object Detection',
    description: 'Detect and classify objects in 3D space using AI models',
    icon: '\u{1F50D}',
    color: '#ef4444',
    endpoint: '/api/object-detection',
    aiEndpoint: '/api/ai/detect-objects',
    aiPromptHint: 'Describe the object detection task (e.g., "Detect vehicles in a parking lot LiDAR scan")',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'detection_model', label: 'Model' },
      { key: 'objects_detected', label: 'Objects', type: 'number' },
      { key: 'confidence_avg', label: 'Confidence %', type: 'number' },
      { key: 'processing_time', label: 'Time' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'name', label: 'Name', required: true },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'detection_model', label: 'Detection Model' },
      { key: 'objects_detected', label: 'Objects Detected', type: 'number' },
      { key: 'confidence_avg', label: 'Avg Confidence %', type: 'number' },
      { key: 'processing_time', label: 'Processing Time' },
      { key: 'input_type', label: 'Input Type', type: 'select', options: ['Point Cloud', 'LiDAR', 'RGB-D', 'Multi-Camera', 'Structured Light', 'CT Scan', 'Photogrammetry'] },
      { key: 'status', label: 'Status', type: 'select', options: ['completed', 'processing', 'error'] },
    ],
  },
  {
    key: 'scene-reconstruction',
    title: 'Scene Reconstruction',
    description: 'Reconstruct 3D scenes from images and sensor data',
    icon: '\u{1F3D7}',
    color: '#f97316',
    endpoint: '/api/scene-reconstruction',
    aiEndpoint: '/api/ai/reconstruct-scene',
    aiPromptHint: 'Describe the scene reconstruction (e.g., "Reconstruct a historic building from 200 drone photos")',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'reconstruction_type', label: 'Type' },
      { key: 'source_images', label: 'Images', type: 'number' },
      { key: 'mesh_quality', label: 'Mesh Quality' },
      { key: 'completeness_percent', label: 'Complete %', type: 'number' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'name', label: 'Name', required: true },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'reconstruction_type', label: 'Type', type: 'select', options: ['Indoor', 'Outdoor', 'Object', 'Heritage', 'Medical'] },
      { key: 'source_images', label: 'Source Images', type: 'number' },
      { key: 'mesh_quality', label: 'Mesh Quality', type: 'select', options: ['Low', 'Medium', 'High', 'Ultra'] },
      { key: 'texture_quality', label: 'Texture Quality', type: 'select', options: ['Low', 'Medium', 'High', 'Ultra'] },
      { key: 'completeness_percent', label: 'Completeness %', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['completed', 'processing', 'error'] },
    ],
  },
  {
    key: 'materials',
    title: 'Materials & Shaders',
    description: 'Create PBR materials and custom shaders for 3D rendering',
    icon: '\u2728',
    color: '#d946ef',
    endpoint: '/api/materials',
    aiEndpoint: '/api/ai/generate-material',
    aiPromptHint: 'Describe the material (e.g., "Iridescent beetle shell material with subsurface scattering")',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'material_type', label: 'Type' },
      { key: 'shader_model', label: 'Shader' },
      { key: 'render_engine', label: 'Engine' },
      { key: 'transparency', label: 'Transparent', type: 'boolean' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'name', label: 'Name', required: true },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'material_type', label: 'Material Type' },
      { key: 'shader_model', label: 'Shader Model' },
      { key: 'render_engine', label: 'Render Engine', type: 'select', options: ['Universal', 'Unreal Engine', 'Unity', 'Blender'] },
      { key: 'pbr_workflow', label: 'PBR Workflow', type: 'select', options: ['Metallic', 'Specular', 'Custom'] },
      { key: 'transparency', label: 'Transparency', type: 'checkbox' },
      { key: 'status', label: 'Status', type: 'select', options: ['ready', 'processing', 'error'] },
    ],
  },
  {
    key: 'asset-library',
    title: '3D Asset Library',
    description: 'Browse, manage and organize your 3D asset collection',
    icon: '\u{1F4E6}',
    color: '#0ea5e9',
    endpoint: '/api/asset-library',
    aiEndpoint: '/api/ai/generate-asset',
    aiPromptHint: 'Describe the 3D asset (e.g., "A low-poly stylized campfire with animated flames")',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'category', label: 'Category' },
      { key: 'format', label: 'Format' },
      { key: 'poly_count', label: 'Polygons', type: 'number' },
      { key: 'file_size', label: 'Size' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'name', label: 'Name', required: true },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'category', label: 'Category' },
      { key: 'format', label: 'Format', type: 'select', options: ['FBX', 'OBJ', 'GLTF', 'USD'] },
      { key: 'poly_count', label: 'Polygon Count', type: 'number' },
      { key: 'file_size', label: 'File Size' },
      { key: 'license_type', label: 'License', type: 'select', options: ['Royalty Free', 'CC-BY', 'CC0', 'Commercial'] },
      { key: 'tags', label: 'Tags (comma separated)', fullWidth: true },
      { key: 'status', label: 'Status', type: 'select', options: ['available', 'archived'] },
    ],
  },
  {
    key: 'holographic',
    title: 'Holographic Content',
    description: 'Create holographic displays and volumetric content',
    icon: '\u{1F48E}',
    color: '#c084fc',
    endpoint: '/api/holographic',
    aiEndpoint: '/api/ai/generate-hologram',
    aiPromptHint: 'Describe the holographic content (e.g., "An interactive holographic anatomy display for medical education")',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'hologram_type', label: 'Type' },
      { key: 'display_tech', label: 'Display Tech' },
      { key: 'resolution', label: 'Resolution' },
      { key: 'depth_layers', label: 'Layers', type: 'number' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'name', label: 'Name', required: true },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'hologram_type', label: 'Hologram Type', type: 'select', options: ['Volumetric', 'Pepper Ghost'] },
      { key: 'display_tech', label: 'Display Technology', type: 'select', options: ['Light Field', 'Holographic Display', 'Pepper Ghost'] },
      { key: 'resolution', label: 'Resolution', type: 'select', options: ['1080p', '4K', '8K'] },
      { key: 'depth_layers', label: 'Depth Layers', type: 'number' },
      { key: 'interactive', label: 'Interactive', type: 'checkbox' },
      { key: 'status', label: 'Status', type: 'select', options: ['ready', 'processing', 'error'] },
    ],
  },
  {
    key: 'spatial-audio',
    title: 'Spatial Audio',
    description: 'Design immersive 3D spatial audio environments and soundscapes',
    icon: '\u{1F3B5}',
    color: '#22d3ee',
    endpoint: '/api/spatial-audio',
    aiEndpoint: '/api/ai/generate-spatial-audio',
    aiPromptHint: 'Describe the spatial audio (e.g., "A rain forest ambience with positioned bird calls and stream")',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'audio_format', label: 'Format' },
      { key: 'channels', label: 'Channels', type: 'number' },
      { key: 'spatialization', label: 'Spatialization' },
      { key: 'duration_seconds', label: 'Duration (s)', type: 'number' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'name', label: 'Name', required: true },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'audio_format', label: 'Format', type: 'select', options: ['Ambisonics', 'Object-Based', 'Binaural'] },
      { key: 'channels', label: 'Channels', type: 'number' },
      { key: 'sample_rate', label: 'Sample Rate', type: 'select', options: ['44100', '48000', '96000'] },
      { key: 'spatialization', label: 'Spatialization', type: 'select', options: ['Ambisonics B-Format', 'Higher Order Ambisonics', 'Object-Based Audio', 'Binaural HRTF', 'HRTF + Room Modeling'] },
      { key: 'hrtf_enabled', label: 'HRTF Enabled', type: 'checkbox' },
      { key: 'duration_seconds', label: 'Duration (seconds)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['ready', 'processing', 'error'] },
    ],
  },
  {
    key: 'scene-generator',
    title: 'AI 3D Scene Generator',
    description: 'Generate complete 3D scenes from text prompts using AI — objects, lighting, materials, and cameras composed automatically',
    icon: '\u{1F3AD}',
    color: '#f43f5e',
    endpoint: '/api/scene-generator',
    aiEndpoint: '/api/ai/generate-scene',
    aiPromptHint: 'Describe the 3D scene you want to generate (e.g., "A cozy coffee shop interior at sunset with warm lighting, wooden tables, potted plants, and a barista behind the counter")',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'scene_type', label: 'Scene Type' },
      { key: 'generation_model', label: 'AI Model' },
      { key: 'objects_count', label: 'Objects', type: 'number' },
      { key: 'lighting_type', label: 'Lighting' },
      { key: 'quality_score', label: 'Quality', type: 'number' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'name', label: 'Name', required: true },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'prompt_text', label: 'Generation Prompt', type: 'textarea', fullWidth: true },
      { key: 'scene_type', label: 'Scene Type', type: 'select', options: ['Interior', 'Exterior', 'Landscape', 'Sci-Fi', 'Fantasy', 'Architectural', 'Product Shot', 'Abstract'] },
      { key: 'generation_model', label: 'AI Model', type: 'select', options: ['SceneDiffusion v3', 'Text2Scene XL', 'NeRF-Studio Pro', 'Gaussian Splat AI', 'Point-E Enhanced', 'Shap-E Pro', 'Custom Pipeline'] },
      { key: 'objects_count', label: 'Objects Count', type: 'number' },
      { key: 'lighting_type', label: 'Lighting', type: 'select', options: ['Natural Daylight', 'Golden Hour', 'Blue Hour', 'Studio Three-Point', 'Dramatic Spotlight', 'Neon/Cyberpunk', 'HDRI Environment', 'Volumetric'] },
      { key: 'render_engine', label: 'Render Engine', type: 'select', options: ['Path Tracer', 'Real-Time RTX', 'Hybrid Ray Trace', 'Rasterization', 'Neural Radiance'] },
      { key: 'output_format', label: 'Output Format', type: 'select', options: ['GLTF', 'USD', 'FBX', 'OBJ', 'NeRF', 'Gaussian Splat'] },
      { key: 'resolution', label: 'Resolution', type: 'select', options: ['1080p', '2K', '4K', '8K'] },
      { key: 'poly_budget', label: 'Polygon Budget', type: 'number' },
      { key: 'generation_time', label: 'Generation Time' },
      { key: 'quality_score', label: 'Quality Score (0-100)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['generating', 'completed', 'refining', 'failed'] },
    ],
  },
  {
    key: 'digital-twins',
    title: 'Digital Twins',
    description: 'Create digital replicas of physical assets with real-time sync',
    icon: '\u{1F504}',
    color: '#84cc16',
    endpoint: '/api/digital-twins',
    aiEndpoint: '/api/ai/generate-digital-twin',
    aiPromptHint: 'Describe the digital twin (e.g., "A smart building twin with HVAC and energy monitoring")',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'twin_type', label: 'Type' },
      { key: 'source_entity', label: 'Source Entity' },
      { key: 'sync_frequency', label: 'Sync Freq' },
      { key: 'sensors_count', label: 'Sensors', type: 'number' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'name', label: 'Name', required: true },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'twin_type', label: 'Twin Type' },
      { key: 'source_entity', label: 'Source Entity' },
      { key: 'sync_frequency', label: 'Sync Frequency', type: 'select', options: ['Real-time', '1 second', '5 seconds', '10 seconds', '30 seconds', '1 minute', '5 minutes'] },
      { key: 'sensors_count', label: 'Sensors Count', type: 'number' },
      { key: 'data_points', label: 'Data Points', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'maintenance', 'offline'] },
    ],
  },
];
